### ISSUE TITLE
This ain't your fucking plugin

### ISSUE THREAD

**Issue by davidgamingzz** [iZeaoGamer/CoolCrates#1]
This plugin belongs to @GiantQuartz

**Comment by TheFixerDevelopment** [comment]
If you read the full notice instad of assuming, then you will know. And stop being a dumb brat, and fucking read.

**Comment by davidgamingzz** [comment]
I’m 99.9% sure that a developer that has this repo as private doesn’t want to have their repo public ;-;

**Comment by TheFixerDevelopment** [comment]
You’re just assuming. That doesn’t mean anything. Whether you like it or not, that’s what happened. Okay? So don’t complain.

**Comment by TheFixerDevelopment** [comment]
Closing issue to prevent further discussion.

**Comment by dresnite** [comment]
You're a piece of shit, thanks for leaking my plugin.

**Comment by dresnite** [comment]
Why do you give credits to yourself? Are you another wanna be dev, right? Pathetic.
